### PR TITLE
docs: Update readme.md to view initialization code in more convenient way

### PR DESCRIPTION
**Pull request by cdefgah**
Reformatted code snippet to show in more convenient way

### CODE REVIEW

**Comment by FreakyAli** [comment]
@cdefgah Thanks appreciate the help 😄

**Comment by cdefgah** [comment]
Glad to help :)

**Comment by cdefgah** [comment]
To get these changes in the master branch of your repository, don't forget to merge this pull request :)

**Comment by FreakyAli** [comment]
@cdefgah Okay sir!

**Comment by FreakyAli** [comment]
@cdefgah Umm, I was planning to merge this over the weekend... Why did you delete it? 😕

**Comment by cdefgah** [comment]
@FreakyAli Will create new one today.

**Comment by cdefgah** [comment]
@FreakyAli Another PR created

**Pull request closed without merging**
