### PR TITLE
Replace SkiaSharp.Svg by Svg.Skia

### LINKED ISSUE #153: Replace SkiaSharp.Svg
SkiaSharp.Svg is deprecated and not being developed further. The last version is from 2018:
https://www.nuget.org/packages/SkiaSharp.Svg/#versions-body-tab

I recommend to replace it with https://github.com/wieslawsoltes/Svg.Skia (which is actively developed and up to date).

If I try to use the FreakyControls package in one of my projects, it causes conflicts with Svg.Skia by pulling in SkiaSharp.Svg.

### PR DESCRIPTION
**Pull request by janusw**
fixes #153

### CODE REVIEW

**Review by rafageist — COMMENTED** [review]
While this migration is a positive step, it should be carefully tested to verify that everything functions as expected with Svg.Skia before merging.

**Comment by FreakyAli** [comment]
> While this migration is a positive step, it should be carefully tested to verify that everything functions as expected with Svg.Skia before merging.

That's the reason you don't see this being merged already, haven't gotten a chance to test this! 

Will only be merged once tested

**Comment by janusw** [comment]
I actually stopped caring by now. 🤷 

Anyhow this library is way too buggy for productive use (for my purposes) and in a pretty bad state (maintenance-wise).

**Comment by FreakyAli** [comment]
> I actually stopped caring by now. 🤷 
> 
> Anyhow this library is way too buggy for productive use (for my purposes) and in a pretty bad state (maintenance-wise).

Oh I'm sorry for the inconveniences, but I have a full time job, I do this in my free time ✌️

**Pull request merged**
