### PR TITLE
fix build errors

### LINKED ISSUE #156: develop branch does not build
When trying to build the current develop branch (at a230d6a56752a446f016199910d2dcd7570d4d40), I get lots of errors regarding `FreakyZoomableView`. It seems like this source file is duplicated (with an extra copy in the `Shared` folder)?

### PR DESCRIPTION
**Pull request by janusw**
* by removing an extra copy of FreakyZoomableView
* fixes #156

### CODE REVIEW

**Comment by FreakyAli** [comment]
@janusw I do have some CI hooks and stuff but they are incomplete, I also need to add tests the unfortunate thing is I have 0 time for the last 3 months

**Comment by janusw** [comment]
> @janusw I do have some CI hooks and stuff but they are incomplete, I also need to add tests the unfortunate thing is I have 0 time for the last 3 months

Incomplete CI is much better than no CI at all ;)
Why don't you simply activate what you have?

Or are you saying it's already running somewhere (where we don't see it)?

**Comment by FreakyAli** [comment]
I think you should be able to see it, its a github action check this location .github/workflows/main_ci.yml

**Comment by janusw** [comment]
> I think you should be able to see it, its a github action check this location .github/workflows/main_ci.yml

Right, it's here (thanks for the pointer):

https://github.com/FreakyAli/Maui.FreakyControls/blob/master/.github/workflows/main_ci.yml


> It's also active as far as I can tell

Actually I do not see it running anywhere.

First problem is: It's only configured to run on the `master` branch (upon push or PR), so it's not checking if the `develop` branch is broken, and it doens't check any PRs to `develop`.

And even on the `master` branch, it does not look like it has run for any of the latest commits. On the last commit, it seems like only main_cd.yml has run, and it failed 😢 
https://github.com/FreakyAli/Maui.FreakyControls/actions/runs/11193473030/job/31118830311

For #154, it's awaiting your approval, apparently.

**Comment by FreakyAli** [comment]
Like I said it's incomplete and I am not finding much time to complete things!

**Comment by janusw** [comment]
I guess the first necessary step would be to merge your master branch into develop, so that the latter also receives the GHA workflows that were added on master. Could you please do that?

Then one can extend those workflows and make sure the build is working ...

**Pull request merged**
